courses/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

app_name = 'courses'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/<int:course_id>/', views.course_detail, name='course_detail'),
    path('courses/<int:course_id>/<int:lesson_id>/', views.lesson_detail, name='lesson_detail'),
    path('create_course/', views.create_course, name='create_course'),
    path('create_lesson/<int:course_id>/', views.create_lesson, name='create_lesson'),
    path('register/', views.registration_view, name='registration'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/profile/', RedirectView.as_view(url='/'), name='profile_redirect'),
]

online_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
]

courses/models.py
import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


class User(AbstractUser):
    RUSSIAN_CITIES = (
        ("moscow", "Москва"),
        ("saint_petersburg", "Санкт-Петербург"),
        ("novosibirsk", "Новосибирск"),
        ("rostov_on_don", "Ростов-на-Дону"),
        ("samara", "Самара"),
        ("omsk", "Омск"),
        ("chelyabinsk", "Челябинск"),
        ("kazan", "Казань"),
        ("nizhny_novgorod", "Нижний Новгород"),
        ("ekaterinburg", "Екатеринбург"),
    )

    is_instructor = models.BooleanField(default=False)
    username = models.CharField(max_length=50, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    birth_date = models.DateField(default=datetime.date(2000, 1, 1))
    email = models.EmailField(unique=True)
    phone_regex = RegexValidator(
        regex=r'^\{9,15}$',
        message="Номер должен состоять только из цифр (от 9 до 15 цифр)"
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=15, blank=True, null=True)
    city = models.CharField(max_length=50, choices=RUSSIAN_CITIES, blank=True)
    GENDER_CHOICES = (
        ('М', 'Мужчина'),
        ('Ж', 'Женщина'),
        ('Д', 'Другое'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='Д')
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)

    class Meta:
        default_related_name = 'custom_users'


class Instructor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    specialization = models.CharField(max_length=100)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_id = models.CharField(max_length=10, unique=True)


class Course(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_taught')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_lessons(self):
        return Lesson.objects.filter(course=self)


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_lesson')
    content = models.TextField()
    order = models.PositiveIntegerField()

    def __str__(self):
        return self.title


class Material(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='lesson_material')
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return self.title


class Progress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='course_progresses')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='progress')
    completed_lessons = models.ManyToManyField(Lesson)

    def __str__(self):
        return f"{self.user} - {self.course}"

courses/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Course, User, Lesson
from django.forms.widgets import SelectDateWidget
from datetime import datetime


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    role = forms.ChoiceField(choices=(('student', 'Студент'), ('instructor', 'Преподаватель')))
    birth_date = forms.DateField(
        widget=SelectDateWidget(
            years=range(1900, datetime.now().year + 1),
            months={
                1: 'Январь',
                2: 'Февраль',
                3: 'Март',
                4: 'Апрель',
                5: 'Май',
                6: 'Июнь',
                7: 'Июль',
                8: 'Август',
                9: 'Сентябрь',
                10: 'Октябрь',
                11: 'Ноябрь',
                12: 'Декабрь',
            },
            empty_label=("Выберите год", "Выберите месяц", "Выберите день"),
        )
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'birth_date', 'gender', 'city', 'avatar']

    def sav(self, commit=True):
        user = super().save(commit=False)
        role = self.cleaned_data.get('role')

        if role == 'student':
            user.is_instructor = False
        elif role == 'instructor':
            user.is_instructor = True

        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'description', 'instructor']


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['title', 'content', 'order']

courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, get_user_model
from django.contrib.auth.views import LoginView
from .models import Course, Lesson
from .forms import CourseForm, RegistrationForm, LoginForm, LessonForm


def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('courses:course_list')
    else:
        form = RegistrationForm()
    return render(request, 'courses/registration.html', {'form': form})


class CustomLoginView(LoginView):
    template_name = 'courses/login.html'
    authentication_form = LoginForm


def create_course(request):
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('courses:course_list')
    else:
        form = CourseForm

    return render(request, 'courses/create_course.html', {'form': form})


def create_lesson(request, course_id):
    course = Course.objects.get(pk=course_id)

    if request.method == 'POST':
        form = LessonForm(request.POST)
        if form.is_valid():
            lesson = form.save(commit=False)
            lesson.course = course
            lesson.save()
            return redirect('courses:course_detail', course_id=course_id)
    else:
        form = LessonForm()

    return render(request, 'courses/create_lesson.html', {'form': form, 'course': course})


def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'courses/course_detail.html', {'course': course})


def lesson_detail(request, lesson_id, course_id):
    lesson = get_object_or_404(Lesson, pk=lesson_id)
    return render(request, 'courses/lesson_detail.html', {'lesson': lesson})


def home_view(request):
    return render(request, 'courses/home.html')

templates/courses/course_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ course.title }}</title>
</head>
<body>
    <h1>{{ course.title }}</h1>
    <p>{{ course.description }}</p>

</body>
</html>

templates/courses/course_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Список Курсов</title>
</head>
<body>
    <h1>Список курсов</h1>
    <ul>
        {% for course in courses %}
            <li><a href="{% url 'courses:course_detail' course.id %}">{{ course.title }}</a> </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/courses/create_course.html
<!DOCTYPE html>
<html>
<head>

    <title>Создание курса</title>
</head>
<body>
    <h1>Создание курса</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать курс</button>
    </form>
</body>
</html>

templates/courses/create_lesson.html
{% extends 'courses/course_detail.html' %}

{% block content %}
    <h2>Создание урока для курса "{{ course.title }}"</h2>
    <form method="post">
        {% csrf_token %}
        {{  form.title.label_tag }}
        {{ form.title }}
        {{ form.content.label_tag }}
        {{ form.content }}
        {{ form.order.label_tag }}
        {{ form.order }}
        <button type="submit">Создать урок</button>
    </form>
    <a href="{% url 'courses:course_detail' course_id=course.id %}">Назад к курсу</a>
{% endblock %}

templates/courses/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"
    <title>Главная страница</title>
</head>
<body>
    <h1>Добро пожаловать на главную страницу</h1>
    {% if user.is_authenticated %}
        <p>Вы вошли в систему как {{ user.first_name }} {{ user.last_name }}</p>
        <a href="{% url 'courses:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'courses:login' %}">Log in</a>
    {% endif %}
    <ul>
        <li><a href="{% url 'courses:create_course' %}">Создать курс</a></li>
        <li><a href="{% url 'courses:course_list' %}">Просмотреть курсы</a></li>
        {% if user.is_authenticated %}
        {% for course in courses %}
            <li><a href="{% url 'courses:create_lesson' course.id %}">Создать урок</a></li>
            <li><a href="{% url 'courses:lesson_detail' course.id %}">Детали урока</a></li>
        {% endfor %}
            <li><a href="{% url 'courses:logout' %}">Log out</a></li>
        {% else %}
            <li><a href="{% url 'courses:login' %}">Log in</a></li>
        {% endif %}

    </ul>
    {% block content %}{% endblock %}
</body>
</html>

templates/courses/lesson_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ lesson.title }}</title>
</head>
<body>
    <h1>{{ lesson.title }}</h1>
    <p>{{ lesson.content}}</p>

    <h2>Материалы</h2>
    <ul>
        {% for material in lesson.material_set.all %}
            <li>{{ material.title }}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/courses/login.html
{% extends 'courses/home.html' %}

{% block content %}
    {% if not user.is_authenticated %}
        <h2>Вход в систему</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.password.label_tag }}
            {{ form.password }}
            {{ form.remember_me }} {{ form.remember_me.label_tag }}
            <button type="submit">Войти</button>
        </form>
    {% endif %}
{% endblock %}

templates/courses/registration.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегестрироваться</button>
</form>